FROM node:20-alpine
WORKDIR /app
ARG VITE_APP_NAME
ARG VITE_APP_URL
ARG VITE_API_BASE_URL
ENV VITE_APP_NAME=$VITE_APP_NAME \
    VITE_APP_URL=$VITE_APP_URL \
    VITE_API_BASE_URL=$VITE_API_BASE_URL \
    NODE_ENV=production \
    PORT=3000 \
    HOST=0.0.0.0
COPY package.json ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build
EXPOSE 3000
CMD ["node", ".output/server/index.mjs"]
