/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SemPermissaoRouteImport } from './routes/sem-permissao'
import { Route as ResetarSenhaRouteImport } from './routes/resetar-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastrarRouteImport } from './routes/cadastrar'
import { Route as AppRouteImport } from './routes/app'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as AppTemplatesRouteImport } from './routes/app.templates'
import { Route as AppServicosRouteImport } from './routes/app.servicos'
import { Route as AppPublicacaoRouteImport } from './routes/app.publicacao'
import { Route as AppProjetosRouteImport } from './routes/app.projetos'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'
import { Route as AppEsteiraRouteImport } from './routes/app.esteira'
import { Route as AppCriadorRouteImport } from './routes/app.criador'
import { Route as AppPrdProjectIdRouteImport } from './routes/app.prd.$projectId'
import { Route as AppCreditosRouteImport } from './routes/app.creditos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppBriefingsRouteImport } from './routes/app.briefings'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as SiteTermosRouteImport } from './routes/_site.termos'
import { Route as SiteTemplatesRouteImport } from './routes/_site.templates'
import { Route as SiteServicosRouteImport } from './routes/_site.servicos'
import { Route as SiteSegmentosRouteImport } from './routes/_site.segmentos'
import { Route as SiteRecursosRouteImport } from './routes/_site.recursos'
import { Route as SitePrivacidadeRouteImport } from './routes/_site.privacidade'
import { Route as SitePlanosRouteImport } from './routes/_site.planos'
import { Route as SiteExemplosRouteImport } from './routes/_site.exemplos'
import { Route as SiteContatoRouteImport } from './routes/_site.contato'
import { Route as SiteAjudaRouteImport } from './routes/_site.ajuda'

const SemPermissaoRoute = SemPermissaoRouteImport.update({
  id: '/sem-permissao',
  path: '/sem-permissao',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetarSenhaRoute = ResetarSenhaRouteImport.update({
  id: '/resetar-senha',
  path: '/resetar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastrarRoute = CadastrarRouteImport.update({
  id: '/cadastrar',
  path: '/cadastrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTemplatesRoute = AppTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppRoute,
} as any)
const AppServicosRoute = AppServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AppRoute,
} as any)
const AppPublicacaoRoute = AppPublicacaoRouteImport.update({
  id: '/publicacao',
  path: '/publicacao',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppEsteiraRoute = AppEsteiraRouteImport.update({
  id: '/esteira',
  path: '/esteira',
  getParentRoute: () => AppRoute,
} as any)
const AppCriadorRoute = AppCriadorRouteImport.update({
  id: '/criador',
  path: '/criador',
  getParentRoute: () => AppRoute,
} as any)
const AppPrdProjectIdRoute = AppPrdProjectIdRouteImport.update({
  id: '/prd/$projectId',
  path: '/prd/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppCreditosRoute = AppCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppBriefingsRoute = AppBriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const SiteTermosRoute = SiteTermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteTemplatesRoute = SiteTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicosRoute = SiteServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteSegmentosRoute = SiteSegmentosRouteImport.update({
  id: '/segmentos',
  path: '/segmentos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteRecursosRoute = SiteRecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => SiteRoute,
} as any)
const SitePrivacidadeRoute = SitePrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => SiteRoute,
} as any)
const SitePlanosRoute = SitePlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteExemplosRoute = SiteExemplosRouteImport.update({
  id: '/exemplos',
  path: '/exemplos',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContatoRoute = SiteContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAjudaRoute = SiteAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/app': typeof AppRouteWithChildren
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/ajuda': typeof SiteAjudaRoute
  '/contato': typeof SiteContatoRoute
  '/exemplos': typeof SiteExemplosRoute
  '/planos': typeof SitePlanosRoute
  '/privacidade': typeof SitePrivacidadeRoute
  '/recursos': typeof SiteRecursosRoute
  '/segmentos': typeof SiteSegmentosRoute
  '/servicos': typeof SiteServicosRoute
  '/templates': typeof SiteTemplatesRoute
  '/termos': typeof SiteTermosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/briefings': typeof AppBriefingsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/criador': typeof AppCriadorRoute
    '/app/prd/$projectId': typeof AppPrdProjectIdRoute
  '/app/esteira': typeof AppEsteiraRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/publicacao': typeof AppPublicacaoRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/ajuda': typeof SiteAjudaRoute
  '/contato': typeof SiteContatoRoute
  '/exemplos': typeof SiteExemplosRoute
  '/planos': typeof SitePlanosRoute
  '/privacidade': typeof SitePrivacidadeRoute
  '/recursos': typeof SiteRecursosRoute
  '/segmentos': typeof SiteSegmentosRoute
  '/servicos': typeof SiteServicosRoute
  '/templates': typeof SiteTemplatesRoute
  '/termos': typeof SiteTermosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/briefings': typeof AppBriefingsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/criador': typeof AppCriadorRoute
  '/app/esteira': typeof AppEsteiraRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/publicacao': typeof AppPublicacaoRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/': typeof SiteIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/app': typeof AppRouteWithChildren
  '/cadastrar': typeof CadastrarRoute
  '/entrar': typeof EntrarRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/resetar-senha': typeof ResetarSenhaRoute
  '/sem-permissao': typeof SemPermissaoRoute
  '/_site/ajuda': typeof SiteAjudaRoute
  '/_site/contato': typeof SiteContatoRoute
  '/_site/exemplos': typeof SiteExemplosRoute
  '/_site/planos': typeof SitePlanosRoute
  '/_site/privacidade': typeof SitePrivacidadeRoute
  '/_site/recursos': typeof SiteRecursosRoute
  '/_site/segmentos': typeof SiteSegmentosRoute
  '/_site/servicos': typeof SiteServicosRoute
  '/_site/templates': typeof SiteTemplatesRoute
  '/_site/termos': typeof SiteTermosRoute
  '/app/admin': typeof AppAdminRoute
  '/app/briefings': typeof AppBriefingsRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/creditos': typeof AppCreditosRoute
  '/app/criador': typeof AppCriadorRoute
  '/app/esteira': typeof AppEsteiraRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/publicacao': typeof AppPublicacaoRoute
  '/app/servicos': typeof AppServicosRoute
  '/app/templates': typeof AppTemplatesRoute
  '/site/$slug': typeof SiteSlugRoute
  '/_site/': typeof SiteIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastrar'
    | '/entrar'
    | '/recuperar-senha'
    | '/resetar-senha'
    | '/sem-permissao'
    | '/ajuda'
    | '/contato'
    | '/exemplos'
    | '/planos'
    | '/privacidade'
    | '/recursos'
    | '/segmentos'
    | '/servicos'
    | '/templates'
    | '/termos'
    | '/app/admin'
    | '/app/briefings'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/criador'
    | '/app/esteira'
    | '/app/perfil'
    | '/app/projetos'
    | '/app/publicacao'
    | '/app/servicos'
    | '/app/templates'
    | '/site/$slug'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastrar'
    | '/entrar'
    | '/recuperar-senha'
    | '/resetar-senha'
    | '/sem-permissao'
    | '/ajuda'
    | '/contato'
    | '/exemplos'
    | '/planos'
    | '/privacidade'
    | '/recursos'
    | '/segmentos'
    | '/servicos'
    | '/templates'
    | '/termos'
    | '/app/admin'
    | '/app/briefings'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/criador'
    | '/app/esteira'
    | '/app/perfil'
    | '/app/projetos'
    | '/app/publicacao'
    | '/app/servicos'
    | '/app/templates'
    | '/site/$slug'
    | '/'
    | '/app'
  id:
    | '__root__'
    | '/_site'
    | '/app'
    | '/cadastrar'
    | '/entrar'
    | '/recuperar-senha'
    | '/resetar-senha'
    | '/sem-permissao'
    | '/_site/ajuda'
    | '/_site/contato'
    | '/_site/exemplos'
    | '/_site/planos'
    | '/_site/privacidade'
    | '/_site/recursos'
    | '/_site/segmentos'
    | '/_site/servicos'
    | '/_site/templates'
    | '/_site/termos'
    | '/app/admin'
    | '/app/briefings'
    | '/app/configuracoes'
    | '/app/creditos'
    | '/app/criador'
    | '/app/esteira'
    | '/app/perfil'
    | '/app/projetos'
    | '/app/publicacao'
    | '/app/servicos'
    | '/app/templates'
    | '/site/$slug'
    | '/_site/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
  AppRoute: typeof AppRouteWithChildren
  CadastrarRoute: typeof CadastrarRoute
  EntrarRoute: typeof EntrarRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  ResetarSenhaRoute: typeof ResetarSenhaRoute
  SemPermissaoRoute: typeof SemPermissaoRoute
  SiteSlugRoute: typeof SiteSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sem-permissao': {
      id: '/sem-permissao'
      path: '/sem-permissao'
      fullPath: '/sem-permissao'
      preLoaderRoute: typeof SemPermissaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resetar-senha': {
      id: '/resetar-senha'
      path: '/resetar-senha'
      fullPath: '/resetar-senha'
      preLoaderRoute: typeof ResetarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastrar': {
      id: '/cadastrar'
      path: '/cadastrar'
      fullPath: '/cadastrar'
      preLoaderRoute: typeof CadastrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/templates': {
      id: '/app/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppTemplatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/servicos': {
      id: '/app/servicos'
      path: '/servicos'
      fullPath: '/app/servicos'
      preLoaderRoute: typeof AppServicosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/publicacao': {
      id: '/app/publicacao'
      path: '/publicacao'
      fullPath: '/app/publicacao'
      preLoaderRoute: typeof AppPublicacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/esteira': {
      id: '/app/esteira'
      path: '/esteira'
      fullPath: '/app/esteira'
      preLoaderRoute: typeof AppEsteiraRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/criador': {
      id: '/app/criador'
      path: '/criador'
      fullPath: '/app/criador'
      preLoaderRoute: typeof AppCriadorRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/creditos': {
      id: '/app/creditos'
      path: '/creditos'
      fullPath: '/app/creditos'
      preLoaderRoute: typeof AppCreditosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/briefings': {
      id: '/app/briefings'
      path: '/briefings'
      fullPath: '/app/briefings'
      preLoaderRoute: typeof AppBriefingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_site/termos': {
      id: '/_site/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof SiteTermosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/templates': {
      id: '/_site/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof SiteTemplatesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/servicos': {
      id: '/_site/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof SiteServicosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/segmentos': {
      id: '/_site/segmentos'
      path: '/segmentos'
      fullPath: '/segmentos'
      preLoaderRoute: typeof SiteSegmentosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/recursos': {
      id: '/_site/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof SiteRecursosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/privacidade': {
      id: '/_site/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof SitePrivacidadeRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/planos': {
      id: '/_site/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof SitePlanosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/exemplos': {
      id: '/_site/exemplos'
      path: '/exemplos'
      fullPath: '/exemplos'
      preLoaderRoute: typeof SiteExemplosRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contato': {
      id: '/_site/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof SiteContatoRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/ajuda': {
      id: '/_site/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof SiteAjudaRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAjudaRoute: typeof SiteAjudaRoute
  SiteContatoRoute: typeof SiteContatoRoute
  SiteExemplosRoute: typeof SiteExemplosRoute
  SitePlanosRoute: typeof SitePlanosRoute
  SitePrivacidadeRoute: typeof SitePrivacidadeRoute
  SiteRecursosRoute: typeof SiteRecursosRoute
  SiteSegmentosRoute: typeof SiteSegmentosRoute
  SiteServicosRoute: typeof SiteServicosRoute
  SiteTemplatesRoute: typeof SiteTemplatesRoute
  SiteTermosRoute: typeof SiteTermosRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAjudaRoute: SiteAjudaRoute,
  SiteContatoRoute: SiteContatoRoute,
  SiteExemplosRoute: SiteExemplosRoute,
  SitePlanosRoute: SitePlanosRoute,
  SitePrivacidadeRoute: SitePrivacidadeRoute,
  SiteRecursosRoute: SiteRecursosRoute,
  SiteSegmentosRoute: SiteSegmentosRoute,
  SiteServicosRoute: SiteServicosRoute,
  SiteTemplatesRoute: SiteTemplatesRoute,
  SiteTermosRoute: SiteTermosRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppBriefingsRoute: typeof AppBriefingsRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppCreditosRoute: typeof AppCreditosRoute
  AppCriadorRoute: typeof AppCriadorRoute
  AppEsteiraRoute: typeof AppEsteiraRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppProjetosRoute: typeof AppProjetosRoute
  AppPublicacaoRoute: typeof AppPublicacaoRoute
  AppServicosRoute: typeof AppServicosRoute
  AppTemplatesRoute: typeof AppTemplatesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppBriefingsRoute: AppBriefingsRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppCreditosRoute: AppCreditosRoute,
  AppCriadorRoute: AppCriadorRoute,
AppPrdProjectIdRoute,
  AppEsteiraRoute: AppEsteiraRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppProjetosRoute: AppProjetosRoute,
  AppPublicacaoRoute: AppPublicacaoRoute,
  AppServicosRoute: AppServicosRoute,
  AppTemplatesRoute: AppTemplatesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
  AppRoute: AppRouteWithChildren,
  CadastrarRoute: CadastrarRoute,
  EntrarRoute: EntrarRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  ResetarSenhaRoute: ResetarSenhaRoute,
  SemPermissaoRoute: SemPermissaoRoute,
  SiteSlugRoute: SiteSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
